name: Terraform vpc-design DESTROY TEST (prod)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type DESTROY-PROD to confirm VPC deletion'
        required: true

permissions:
  id-token: write
  contents: read


# Prevents state-lock conflicts
concurrency: 
  group: terraform-prod-vpc
  cancel-in-progress: false

jobs:
  destroy:
    name: Destroy VPC in PROD
    runs-on: ubuntu-latest
    environment: prod



    env:
      AWS_REGION: eu-central-1   # change if needed
      TF_IN_AUTOMATION: true
      WORKING_DIR: networking/network-design/vpc-design/envs/prod

    steps:

      - name: Safety check
        run: |
          if [ "${{ inputs.confirm }}" != "DESTROY-PROD" ]; then
            echo "Confirmation failed. Aborting."
            exit 1
          fi

    # The checkout action fetches the repository code and makes it available to the workflow.
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug environment variables
        run: |
          echo "AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}"
          echo "AWS_REGION: ${{ vars.AWS_REGION }}"

    #   - name: Debug repo structure
    #     run: |
    #         pwd
    #         tree -L 3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{vars.AWS_ROLE_ARN}}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=destroy.tfplan -input=false
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Destroy
        run: terraform apply -auto-approve "destroy.tfplan"
        working-directory: ${{ env.WORKING_DIR }}
