name: Terraform vpc-design DESTROY TEST (prod)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type DESTROY-PROD to confirm VPC deletion'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1   # change if needed

    steps:

      - name: Safety check
        run: |
          if [ "${{ inputs.confirm }}" != "DESTROY-PROD" ]; then
            echo "Confirmation failed. Aborting."
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug repo structure
        run: |
            pwd
            tree -L 3
            ls -R networking/network-design/vpc-design
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::058264462678:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: networking/network-design/vpc-design/envs/prod


      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
        working-directory: networking/network-design/vpc-design/envs/prod
